#!/bin/sh
set -e -u -o pipefail

cd /app/ovpn/config/pia

set -- "$@" '--config' "${REGION:-US East}.ovpn"


if [ -n "$USERNAME" -a -n "$PASSWORD" ]; then
	echo "$USERNAME" > auth.conf
	echo "$PASSWORD" >> auth.conf
	chmod 600 auth.conf
	set -- "$@" '--auth-user-pass' 'auth.conf'
else
	echo "OpenVPN credentials not set. Exiting."
	exit 1
fi

openvpn "$@" --auth-nocache --script-security 2 --up "/app/sockd.sh"
